config/routes.rb
Rails.application.routes.draw do
  get '/rooms/show_piles', to: 'rooms#show_piles'

  get '/rooms/new_join', to: 'rooms#new_join'
  post '/rooms/create_join', to: 'rooms#create_join'

  post 'rooms/show_hand', to: 'rooms#show_hand'
  resources :rooms

  resources :users

  match '/login', to: 'user_sessions#new', via: :get
  match '/login', to: 'user_sessions#create', via: :post
  match '/logout', to: 'user_sessions#destroy', via: :post
  match '/dashboard', to: 'user_sessions#index', via: :get

  root to: redirect('/dashboard')

  resources :piles do
    collection do
      get 'get_from_draw'
      get 'discard'
      get 'show_transfer'
      post 'draw_cards_from_deck'
      post 'transfer_card'
      post 'transfer_to_discard'
    end
  end
  match '/create_pile', to: 'piles#new', via: :post
  match '/create_deck', to: 'piles#create_deck', via: :post

end

app/models/pile.rb
class Pile < ActiveRecord::Base
  has_many :cards
  belongs_to :room
  after_update :signal_pile_change

  def signal_pile_change
    LobbyUpdateJob.perform_later(self.room_id, self.id)
  end

  def self.transfer(source_pile, destination_pile, cards)
    card_difference = cards.keys.count
    destination_pile[:card_count] = destination_pile.cards.count + card_difference
    source_pile[:card_count] = source_pile.cards.count - card_difference
    destination_pile.save
    source_pile.save
    cards.keys.each do |card|
      destination_pile.cards << Card.find_by(id: card)
    end
  end
end

app/controllers/piles_controller.rb
class PilesController < ApplicationController
  before_action :set_current_user
  protect_from_forgery with: :null_session

  def pile_params
    params.require(:pile).permit(:name, :private_pile, :creator, :source_pile_id, :destination_pile_id)
  end

  def index
    @piles = Pile.all
  end

  def new
    render(partial: 'partials/create_pile') if request.xhr?
  end

  def new_deck
  end

  def create
    #room_id = params[:room_id]
    room = Room.find_by(id: params[:room_id])
    private_pile = params[:private_pile]
    #name = params[:pile][:name]
    #creator = params[:pile][:creator]
    @pile = Pile.create!(name: params[:pile][:name], creator: params[:pile][:creator], private_pile: private_pile, card_count: 0, room_id: params[:room_id])
    room.piles << @pile
    room.save!
    redirect_to room_path({id: params[:room_id]}), flash: { notice: "#{@pile.name} was successfully created."}
    #flash[:notice] = "#{@pile.name} was successfully created." #@pile.name
    # redirect_to room_path({:id => room_id}) and return
  end

  def show_transfer
    @piles = Room.find_by_id(params[:room_id]).piles
    render(partial: 'partials/transfer_cards') if request.xhr?
  end

  def draw_cards_from_deck
    num_cards = params[:pile][:num_cards].to_i
    deck = Pile.find_by(name: "Deck", room_id: params[:room_id])
    destination_pile = Pile.find_by(name: "#{@current_user.user_id}'s Hand", room_id: params[:room_id]) #this represents the format an automatically created hand should get
    if num_cards > deck.cards.count
      redirect_to room_path({id: params[:room_id]}), flash: { notice: 'There are not enough cards in the deck. Please try again or wait until the deck is replenished.'} and return
    end
    deck_count = deck.cards.count
    list_of_cards = (0...deck_count).to_a.sample(num_cards)
    list_of_cards.each do |card_num|
      destination_pile.cards << deck.cards[card_num]
    end
    destination_pile[:card_count] = destination_pile[:card_count] + num_cards
    deck[:card_count] = deck[:card_count] - num_cards
    deck.save
    destination_pile.save
    redirect_to room_path({id: params[:room_id]}), flash: { notice: "#{num_cards} card(s) transferred from Deck!"} and
        return unless request.xhr?

    # https://stackoverflow.com/questions/4632271/render-nothing-true-returns-empty-plaintext-file/18059789
    render plain: 'drawn', status: 200, content_type: 'text/html' if request.xhr?

  end

  def transfer_card
    begin
      source_pile = Pile.find pile_params[:source_pile_id]
      destination_pile = Pile.find pile_params[:destination_pile_id]
    rescue ActiveRecord::RecordNotFound
      redirect_to room_path({id: params[:room_id]}) and return
    end
    if params[:the_cards].nil?
      redirect_to room_path({id: params[:room_id]}) and return
    end
    Pile.transfer(source_pile, destination_pile, params[:the_cards])
  end

  def get_from_draw
    @room = Room.find_by(id: params[:room_id])
    render(partial: 'partials/draw_card') if request.xhr?
  end

  def discard
    @player_pile = Pile.find_by(name: "#{@current_user.user_id}'s Hand", room_id: params[:room_id])
    @thecards = @player_pile.cards
    render(partial: 'partials/discard_cardy') if request.xhr?
  end

  def transfer_to_discard
    source_pile = Pile.find_by(name: params[:source_pile_name], room_id: params[:room_id])
    @destination_pile = Pile.find_by(name: params[:pile][:name2], room_id: params[:room_id])
    if @destination_pile.nil?
      redirect_to room_path({id: params[:room_id]}), flash: { notice: "(transfer_card) This is not a pile in the database. Please try again."} and return #piles_pile_homepage_path and return
    end
    if params[:the_cards].nil?
      redirect_to room_path({id: params[:room_id]}), flash: { notice: "No cards selected"} and return
    end
    Pile.transfer source_pile, @destination_pile, params[:the_cards]
    redirect_to room_path({id: params[:room_id]}), flash: { notice: "Card(s) successfully discarded!"}
  end

end

app/views/piles/discard.html.erb
<h3><%= link_to 'Game Room', room_path({:id => params[:room_id]}), :class => 'btn btn-primary' %></h3>
<h2>Discard Cards</h2>

<%= form_tag transfer_to_discard_piles_path({:room_id => params[:room_id], :source_pile_name => @player_pile.name, :pile => {:name2 => 'Discard Pile'}}), :id => 'the_cards_form' do %>
  <table class="table table-striped col-md-12">
    <thead>
    <tr>
      <th>Your Hand</th>
    </tr>
    </thead>
    <tbody>
    <% @thecards.each do |card| %>
      <tr>
        <td>
          <%= card.name %>
        </td>
        <td>
          <%=check_box_tag "the_cards[#{card.id}]", nil, nil, {:id => "checkbox_#{card.name}"}%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <%= submit_tag "Discard Card(s)", :class => 'btn btn-primary', :id => 'discard_the_cards' %>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/piles/draw_cards.html.erb
<%= form_tag piles_draw_cards_from_deck_path({:room_id => @room.id}), :class => 'form' do %>
  <%= label :pile, :num_cards, "How many?", :class => 'col-form-label' %>
  <%= text_field :pile, 'num_cards', :class => 'form-control'%>
  <%= submit_tag 'Submit',  :class => 'btn btn-primary'%>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/piles/index.html.erb
<h2>All Piles</h2>
<table class="table table-striped col-md-12">
  <thead>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Count</th>
  </tr>
  </thead>
  <tbody>
  <% @piles.each do |pile| %>
    <tr>
      <td>
        <%= pile.name%>
      </td>
      <td>
        <%= pile.creator%>
      </td>
      <td>
        <%= pile.card_count%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/piles/new.html.erb
<h2>Create Pile!!</h2>

<%= form_tag piles_path({:room_id => params[:room_id]}), :class => 'form' do %>
  <%= label :pile, :name, 'Pile Name:', :class => 'col-form-label' %>
  <%= text_field :pile, 'name', :class => 'form-control col-1' %>
  <%= label :pile, :creator, 'Your Name:', :class => 'col-form-label'  %>
  <%= text_field :pile, 'creator', :class => 'form-control col-1' %>
  <%= label :pile, :private_pile, 'Pile is private?:', :class => 'col-form-label'  %>
  <%= select_tag :private_pile, options_for_select([:true, :false]) %>
  <br/>
  <%= submit_tag 'Create my pile!', :class => 'btn btn-primary' %>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/piles/show.html.erb
<h3><%= link_to 'Game Room', room_path({:id => params[:room_id]}), :class => 'btn btn-primary' %></h3>
<h2>Transfer Card!!</h2>
<table class="table table-striped col-md-12">
  <thead>
  <tr>
    <th>Pile</th>
  </tr>
  </thead>
  <tbody>
  <%= form_tag piles_transfer_card_path({:room_id => params[:room_id], :source_pile_name => @source_pile.name}), :id => 'transfer_cards_form' do
    @cards.each do |card| %>
    <tr>
      <td>
        <% if (@is_private) %>
          <%= card.id %>
        <% elsif !(@is_private) %>
          <%= card.id %>
          <%= card.name %>
        <% end %>
      </td>
      <td>
        <%=check_box_tag "the_cards[#{card.id}]", nil, nil, {:id => "checkbox_#{card.name}"}%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
  <%= label :pile, :name2, 'Destination Pile:', :class => 'col-form-label' %>
  <%= text_field :pile, 'name2', :class => 'form-control col-1' %>
  <br/>
  <%= submit_tag 'Transfer Card(s)', :class => 'btn btn-primary', :id => 'transfer_cards' %>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>