config/routes.rb
Rails.application.routes.draw do
  get '/rooms/show_piles', to: 'rooms#show_piles'

  get '/rooms/new_join', to: 'rooms#new_join'
  post '/rooms/create_join', to: 'rooms#create_join'

  post 'rooms/show_hand', to: 'rooms#show_hand'
  resources :rooms

  resources :users

  match '/login', to: 'user_sessions#new', via: :get
  match '/login', to: 'user_sessions#create', via: :post
  match '/logout', to: 'user_sessions#destroy', via: :post
  match '/dashboard', to: 'user_sessions#index', via: :get

  root to: redirect('/dashboard')

  resources :piles do
    collection do
      get 'get_from_draw'
      get 'discard'
      get 'show_transfer'
      post 'draw_cards_from_deck'
      post 'transfer_card'
      post 'transfer_to_discard'
    end
  end
  match '/create_pile', to: 'piles#new', via: :post
  match '/create_deck', to: 'piles#create_deck', via: :post

end

app/views/partials/_create_pile.html.erb
<h2>Create Pile!!</h2>

<%= form_tag piles_path({:room_id => params[:room_id]}), :class => 'form' do %>
  <%= label :pile, :name, 'Pile Name:', :class => 'col-form-label' %>
  <%= text_field :pile, 'name', :class => 'form-control col-1' %>
  <%= label :pile, :creator, 'Your Name:', :class => 'col-form-label'  %>
  <%= text_field :pile, 'creator', :class => 'form-control col-1' %>
  <%= label :pile, :private_pile, 'Pile is private?:', :class => 'col-form-label'  %>
  <%= select_tag :private_pile, options_for_select([:true, :false]) %>
  <br/>
  <%= submit_tag 'Create my pile!', :class => 'btn btn-primary' %>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/partials/_discard_cardy.html.erb
<h3><%= link_to 'Game Room', room_path({:id => params[:room_id]}), :class => 'btn btn-primary' %></h3>
<h2>Discard Cards</h2>

<%= form_tag transfer_to_discard_piles_path({:room_id => params[:room_id], :source_pile_name => @player_pile.name, :pile => {:name2 => 'Discard Pile'}}), :id => 'the_cards_form' do %>
  <table class="table table-striped col-md-12">
    <thead>
    <tr>
      <th>Your Hand</th>
    </tr>
    </thead>
    <tbody>
    <% @thecards.each do |card| %>
      <tr>
        <td>
            <%= card.name %>
        </td>
        <td>
          <%=check_box_tag "the_cards[#{card.id}]", nil, nil, {:id => "checkbox_#{card.name}"}%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <%= submit_tag 'Discard Card(s)', :class => 'btn btn-primary', :id => 'discard_the_cards' %>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/partials/_draw_card.html.erb
<%= form_tag draw_cards_from_deck_piles_path({:room_id => params[:room_id]}), :class => 'form', :id => 'draw_form',
    remote: true, :authenticity_token => true do %>
  <%= label :pile, :num_cards, "How many?", :class => 'col-form-label' %>
  <%= text_field :pile, 'num_cards', :class => 'form-control'%>
  <%= submit_tag 'Submit',  :class => 'btn btn-primary'%>
<% end %>
<%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>

app/views/partials/_hide_hand.html.erb
<%= link_to 'Hide Hand', rooms_show_hand_path, :class => 'btn btn-outline-primary', id: 'show_hand_form', method: :post, remote: true, :authenticity_token => true %>

app/views/partials/_login.html.erb
<h2>Login</h2>

<%= form_tag login_path, :method => :post, :class => 'form' do %>
  <%= label :user, :email, 'Email',  :class => 'col-form-label'  %>
  <%= text_field :user, 'email', id: 'loginEmail', :class => 'form-control' %>
  <%= label :user, :password, 'Password',  :class => 'col-form-label' %>
  <%= password_field :user, 'password', id: 'loginPass', :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Login to my account', id: 'login_submit' %>
<% end %>
<%= button_to 'Sign-up for an account', new_user_path, :method => :get, id: 'signup' %>
<%= button_to 'Cancel', root_path, :method => :get, id: 'cancelLogin' %>

app/views/partials/_show_hand.html.erb
<%= link_to 'Show Hand', rooms_show_hand_path, :class => 'btn btn-outline-primary', id: 'show_hand_form', method: :post, remote: true, :authenticity_token => true %>

app/views/partials/_show_pile.html.erb
<table class="playingCards faceImages cardsTable dataTable" id="card-table">
  <% @room.piles.each do |pile| %>
    <tr id=<%="#{pile.id}"%> style="display:none;">
      <% Card.where(pile_id: pile.id).each do |card| %>
        <td>
          <% if pile.private_pile %>
              <a class="card back"></a>
          <% else %>
              <a class="card rank-<%=card.rank.downcase%> <%= card.suit %>">
                <span class="rank"><%= card.rank %></span>
                <span class="suit">&<%= card.suit %>;</span>
              </a>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/partials/_transfer_cards.html.erb
<h3 style="color: white;" data-source-pile="<%= @piles.select{ |pile| pile.creator == @current_user.user_id }[0].id %>" id="transfer_cards_details_header">Transfer Card!!</h3>

  <%= form_tag transfer_card_piles_path({:room_id => params[:room_id]}), :id => 'transfer_cards_form', remote: true, :authenticity_token => true do %>
  <%= label :pile, :source_pile_name, 'Transfer From:', :class => 'row-form-label', style: "color: white" %>
  <%= select :pile, :source_pile_id, options_from_collection_for_select(
      @piles.select { |pile| !pile.private_pile or pile.creator == @current_user.user_id }, "id", "name"), :include_blank => true %>
  <%= label :pile, :destination_pile_name, 'To:', :class => 'row-form-label', style: "color: white" %>
  <%= select :pile, :destination_pile_id, options_from_collection_for_select(@piles, "id", "name"), :include_blank => true %>
  <p style="color: white;">Cards to Transfer:</p>
  <% @piles.each do |pile| %>
    <% pile_table_elem_id = "pile_table_#{pile.id}" %>
    <div style="padding-top: 5px; padding-bottom: 5px; height: 210px; overflow-y: auto; display: none;">
      <table class="table table-striped card-table col-md-12" id=<%= pile_table_elem_id %> style="display:table;">
        <tbody>
        <% is_private = pile.private_pile %>
        <% pile.cards.each do |card| %>
          <tr>
            <td style="color:white;">
              <% if is_private and pile.creator != @current_user.user_id %>
                <span style="font-size:25px; padding-right: 5px;">&#x1F0F4;</span>
                Facedown Card
              <% elsif !is_private or pile.creator == @current_user.user_id %>
                <span style="font-size:25px; padding-right: 5px;">&#x<%= card.unicode_value %></span>
                <%= card.name %>
              <% end %>
            </td>
            <td>
              <%=check_box_tag "the_cards[#{card.id}]", nil, nil, {:id => "checkbox_#{card.name}"}%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
  </br>
    <%= submit_tag 'Transfer Card(s)', :class => 'btn btn-primary', :id => 'transfer_cards' %>
  <% end %>
  <%= button_to 'Cancel', room_path({:id => params[:room_id]}), :method => :get, :id => 'cancel' %>