config/routes.rb
Rails.application.routes.draw do
  get '/rooms/show_piles', to: 'rooms#show_piles'

  get '/rooms/new_join', to: 'rooms#new_join'
  post '/rooms/create_join', to: 'rooms#create_join'

  post 'rooms/show_hand', to: 'rooms#show_hand'
  resources :rooms

  resources :users

  match '/login', to: 'user_sessions#new', via: :get
  match '/login', to: 'user_sessions#create', via: :post
  match '/logout', to: 'user_sessions#destroy', via: :post
  match '/dashboard', to: 'user_sessions#index', via: :get

  root to: redirect('/dashboard')

  resources :piles do
    collection do
      get 'get_from_draw'
      get 'discard'
      get 'show_transfer'
      post 'draw_cards_from_deck'
      post 'transfer_card'
      post 'transfer_to_discard'
    end
  end
  match '/create_pile', to: 'piles#new', via: :post
  match '/create_deck', to: 'piles#create_deck', via: :post

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :users
  has_many :piles
  before_create do
    if self.max_players.nil?
      self.max_players = 5
    end
  end
  #TODO: Add validations to handle invalid or empty inputs
  def self.create_room!(room_params)
    room_params[:room_code] = SecureRandom.random_number(9999999999)
    Room.create!(room_params)
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_current_user
  def new
  end

  def create
    @room = Room.create_room!(:name => params[:room_name],
                         :max_players => params[:max_players],
                         :game_type => params[:game_type],
                         :private => params[:private])

    @room.users << @current_user
    pile = Pile.create(name: "#{@current_user.user_id}'s Hand", creator: @current_user.user_id, private_pile: true, card_count: 0)
    @pile = Pile.create!(name: "Deck", creator: "The Game", private_pile: true, card_count: 52, room_id: @room.id)
    discard_pile = Pile.create!(name: "Discard Pile", creator: "The Game", private_pile: false , card_count: 0, room_id: @room.id)
    @room.piles << @pile
    @room.piles << discard_pile
    Card.create([{name: "Ace of Spades", pile_id: @pile.id, unicode_value: "1F0A1", suit: "spades", rank: "A"},
                 {name: "Two of Spades", pile_id: @pile.id, unicode_value: "1F0A2", suit: "spades", rank: "2"},
                 {name: "Three of Spades", pile_id: @pile.id, unicode_value: "1F0A3", suit: "spades", rank: "3"},
                 {name: "Four of Spades", pile_id: @pile.id, unicode_value: "1F0A4", suit: "spades", rank: "4"},
                 {name: "Five of Spades", pile_id: @pile.id, unicode_value: "1F0A5", suit: "spades", rank: "5"},
                 {name: "Six of Spades", pile_id: @pile.id, unicode_value: "1F0A6", suit: "spades", rank: "6"},
                 {name: "Seven of Spades", pile_id: @pile.id, unicode_value: "1F0A7", suit: "spades", rank: "7"},
                 {name: "Eight of Spades", pile_id: @pile.id, unicode_value: "1F0A8", suit: "spades", rank: "8"},
                 {name: "Nine of Spades", pile_id: @pile.id, unicode_value: "1F0A9", suit: "spades", rank: "9"},
                 {name: "Ten of Spades", pile_id: @pile.id, unicode_value: "1F0AA", suit: "spades", rank: "10"},
                 {name: "Jack of Spades", pile_id: @pile.id, unicode_value: "1F0AB", suit: "spades", rank: "J"},
                 {name: "Queen of Spades", pile_id: @pile.id, unicode_value: "1F0AD", suit: "spades", rank: "Q"},
                 {name: "King of Spades", pile_id: @pile.id, unicode_value: "1F0AE", suit: "spades", rank: "K"},
                 {name: "Ace of Hearts", pile_id: @pile.id, unicode_value: "1F0B1", suit: "hearts", rank: "A"},
                 {name: "Two of Hearts", pile_id: @pile.id, unicode_value: "1F0B2", suit: "hearts", rank: "2"},
                 {name: "Three of Hearts", pile_id: @pile.id, unicode_value: "1F0B3", suit: "hearts", rank: "3"},
                 {name: "Four of Hearts", pile_id: @pile.id,unicode_value: "1F0B4", suit: "hearts", rank: "4"},
                 {name: "Five of Hearts", pile_id: @pile.id, unicode_value: "1F0B5", suit: "hearts", rank: "5"},
                 {name: "Six of Hearts", pile_id: @pile.id, unicode_value: "1F0B6", suit: "hearts", rank: "6"},
                 {name: "Seven of Hearts", pile_id: @pile.id, unicode_value: "1F0B7", suit: "hearts", rank: "7"},
                 {name: "Eight of Hearts", pile_id: @pile.id, unicode_value: "1F0B8", suit: "hearts", rank: "8"},
                 {name: "Nine of Hearts", pile_id: @pile.id, unicode_value: "1F0B9", suit: "hearts", rank: "9"},
                 {name: "Ten of Hearts", pile_id: @pile.id, unicode_value: "1F0BA", suit: "hearts", rank: "10"},
                 {name: "Jack of Hearts", pile_id: @pile.id, unicode_value: "1F0BB", suit: "hearts", rank: "J"},
                 {name: "Queen of Hearts", pile_id: @pile.id, unicode_value: "1F0BD", suit: "hearts", rank: "Q"},
                 {name: "King of Hearts", pile_id: @pile.id, unicode_value: "1F0BE", suit: "hearts", rank: "K"},
                 {name: "Ace of Clubs", pile_id: @pile.id, unicode_value: "1F0D1", suit: "clubs", rank: "A"},
                 {name: "Two of Clubs", pile_id: @pile.id, unicode_value: "1F0D2", suit: "clubs", rank: "2"},
                 {name: "Three of Clubs", pile_id: @pile.id, unicode_value: "1F0D3", suit: "clubs", rank: "3"},
                 {name: "Four of Clubs", pile_id: @pile.id, unicode_value: "1F0D4", suit: "clubs", rank: "4"},
                 {name: "Five of Clubs", pile_id: @pile.id, unicode_value: "1F0D5", suit: "clubs", rank: "5"},
                 {name: "Six of Clubs", pile_id: @pile.id, unicode_value: "1F0D6", suit: "clubs", rank: "6"},
                 {name: "Seven of Clubs", pile_id: @pile.id, unicode_value: "1F0D7", suit: "clubs", rank: "7"},
                 {name: "Eight of Clubs", pile_id: @pile.id, unicode_value: "1F0D8", suit: "clubs", rank: "8"},
                 {name: "Nine of Clubs", pile_id: @pile.id, unicode_value: "1F0D9", suit: "clubs", rank: "9"},
                 {name: "Ten of Clubs", pile_id: @pile.id, unicode_value: "1F0DA", suit: "clubs", rank: "10"},
                 {name: "Jack of Clubs", pile_id: @pile.id, unicode_value: "1F0DB", suit: "clubs", rank: "J"},
                 {name: "Queen of Clubs", pile_id: @pile.id, unicode_value: "1F0DD", suit: "clubs", rank: "Q"},
                 {name: "King of Clubs", pile_id: @pile.id, unicode_value: "1F0DE", suit: "clubs", rank: "K"},
                 {name: "Ace of Diamonds", pile_id: @pile.id, unicode_value: "1F0C1", suit: "diams", rank: "A"},
                 {name: "Two of Diamonds", pile_id: @pile.id, unicode_value: "1F0C2", suit: "diams", rank: "2"},
                 {name: "Three of Diamonds", pile_id: @pile.id, unicode_value: "1F0C3", suit: "diams", rank: "3"},
                 {name: "Four of Diamonds", pile_id: @pile.id, unicode_value: "1F0C4", suit: "diams", rank: "4"},
                 {name: "Five of Diamonds", pile_id: @pile.id, unicode_value: "1F0C5", suit: "diams", rank: "5"},
                 {name: "Six of Diamonds", pile_id: @pile.id, unicode_value: "1F0C6", suit: "diams", rank: "6"},
                 {name: "Seven of Diamonds", pile_id: @pile.id, unicode_value: "1F0C7", suit: "diams", rank: "7"},
                 {name: "Eight of Diamonds", pile_id: @pile.id, unicode_value: "1F0C8", suit: "diams", rank: "8"},
                 {name: "Nine of Diamonds", pile_id: @pile.id, unicode_value: "1F0C9", suit: "diams", rank: "9"},
                 {name: "Ten of Diamonds", pile_id: @pile.id, unicode_value: "1F0CA", suit: "diams", rank: "10"},
                 {name: "Jack of Diamonds", pile_id: @pile.id, unicode_value: "1F0CB", suit: "diams", rank: "J"},
                 {name: "Queen of Diamonds", pile_id: @pile.id, unicode_value: "1F0CD", suit: "diams", rank: "Q"},
                 {name: "King of Diamonds", pile_id: @pile.id, unicode_value: "1F0CE", suit: "diams", rank: "K"}
                ])
    @room.piles << pile

    [1,2,3,4,5,6,7,8,9,10].map{|index| Pile.create(name: "General #{index}", creator: "The Game", private_pile: false, card_count: 0, room_id: @room.id) }
    # Pile.create(name: "Discard Pile", creator: "The Game", private_pile: false, card_count: 0, room_id: @room.id)

    @room.save!
    flash[:notice] = "Welcome to your newly created room, #{@room.name}"
    redirect_to room_path(@room)
  end

  def show
    id = params[:id]
    @room = Room.find(id)
    @draw_pile = Pile.find_by(room_id: @room.id, name: "Deck", creator: "The Game")
    @draw_cards = translate_cards_to_array(Card.where(pile_id: @draw_pile.id))
    @discard_pile = Pile.find_by(room_id: @room.id, name: "Discard Pile", creator: "The Game")
    @center_piles = []
    Pile.where(:room_id => @room, :creator => "The Game").each do |pile|
      if pile.name.include?("General")
        @center_piles << pile
      end
    end

    @piles = Pile.all
    user_hand_name = "#{@current_user.user_id}'s Hand"
    @user_hand = Pile.find_by(room_id: id, name: user_hand_name)
    user_cards = Card.where(pile_id: @user_hand.id)
    @fan = user_cards.length <= 13

    @card_list = translate_cards_to_array(user_cards)
    render partial: 'show_game_room' if request.xhr?
  end

  def new_join
  end

  def create_join
    begin
      @room = Room.find_by!(:room_code => params[:id])
      existing_user_hand_query = Pile.where(name: "#{@current_user.user_id}'s Hand", room_id: "#{@room.id}")
      unless existing_user_hand_query.empty?
        flash[:notice] = "#{@current_user.user_id}, welcome back to #{@room.name}"
        redirect_to room_path(@room) and return
      end
      if @room.users.count < @room.max_players
        @room.users << @current_user
        pile = Pile.create(name: "#{@current_user.user_id}'s Hand", creator: @current_user.user_id, private_pile: true, card_count: 0)
        @room.piles << pile
        @room.save!
        flash[:notice] = "#{@current_user.user_id}, welcome to #{@room.name}"
        redirect_to room_path(@room)
      else
        flash[:notice] = "Sorry, #{@room.name} is already at full capacity"
        redirect_to dashboard_path
      end
    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "A room with that code does not exist."
      redirect_to rooms_new_join_path
    end
  end

  def show_hand
    room_id = @current_user.room_id
    user_hand = "#{@current_user.user_id}'s Hand"
    pile = Pile.find_by(room_id: room_id, name: user_hand)
    if pile.private_pile
      pile.private_pile = false
      pile.save
      render partial: 'partials/hide_hand' if request.xhr?
    else
      pile.private_pile = true
      pile.save
      render partial: 'partials/show_hand' if request.xhr?
    end
  end
  
  private

  def translate_cards_to_array(card_list)
    card_list.map do |card|
      if card.name.split[2] == "Diamonds"
        suit = "diams"
      else
        suit = card.name.split[2].downcase
      end
      card_name = translate_rank(card.name.split[0])
      [card_name, suit]
    end
  end

  def translate_rank(rank)
    case rank
      when "Ace"
        "A"
      when "Two"
        "2"
      when "Three"
        "3"
      when "Four"
        "4"
      when "Five"
        "5"
      when "Six"
        "6"

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_show_game_room.html.erb
<div id="room-information">
  <h2>Welcome To <%= @room.name %></h2>
  <h2>Room Join Code: <%= @room.room_code %></h2>
</div>
<div class="base-room">
  <div class="left-panel">
    </br>
    <% @room.piles.select{ |pile| pile.name.include? "'s Hand" }.each do |pile| %>
      <% if pile.creator != @current_user.user_id %>
        <%= button_tag "#{pile.name}", type: "button", class: "btn btn-outline-dark", onclick: "show_pile(#{pile.id})"%>
        </br>
      <% end %>
    <% end %>
  </div>
  <div class="center-panel">
    <div class="top-center-panel w3-panel" id="show-pile-panel">
      <%= render "partials/show_pile" %>
    </div>
    <div class="middle-center-panel">
      <div class="draw-discard">
        <div class="playingCards  faceImages">
          <ul class="deck" id ="draw">
            <% if @draw_pile.cards.count == 0 %>
              <li>
                <a class="card cardOutline">+</a>
              </li>
            <% else %>
              <% @draw_pile.cards.each do |card| %>
                <li>
                  <a class="card back"></a>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="playingCards  faceImages">
          <ul class="deck" id ="discard">
            <% if @discard_pile.cards.count == 0 %>
              <li>
                <a class="card cardOutline">X</a>
              </li>
            <% else %>
              <% @discard_pile.cards.each do |card| %>
                <li>
                  <a onclick="show_pile(<%= @discard_pile.id %>)" class="card rank-<%= card.rank.downcase %> <%=card.suit%>">
                    <span class="rank"><%=card.rank%></span>
                    <span class="suit">&<%=card.suit%>;</span>
                  </a>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>

      </div>
      <div class="piles">
        <%  @center_piles.each do |pile|%>

          <div class="centerPiles playingCards faceImages">
            <ul class="deck" id =<% pile.name %>>
              <% if pile.cards.count == 0 %>
                <li>
                  <a class="card cardOutline"><%=pile.name.split[1]%></a>
                </li>
              <% else %>
                <% pile.cards.each do |card| %>
                  <li>
                    <a onclick="show_pile(<%= pile.id %>)" class="card rank-<%= card.rank.downcase %> <%=card.suit%>">
                      <span class="rank"><%=card.rank%></span>
                      <span class="suit">&<%=card.suit%>;</span>
                    </a>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class="playingCards faceImages bottom-center-panel" id="root-playing-card">
      <ul class="hand" id ="users-cards">
        <% @card_list.each do |card| %>
          <li>
            <a class="card rank-<%= card[0].downcase %> <%=card[1]%>">
              <span class="rank"><%=card[0]%></span>
              <span class="suit">&<%=card[1]%>;</span>
            </a>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
  <div class="right-panel">
    <!--    <ActionsPanel/>-->
    <div id="game-actions">
      <%= form_tag get_from_draw_piles_path({:room_id => @room.id}), :class => 'form' do %>
        <%= submit_tag 'Draw', :type => "button", :class => 'btn btn-outline-primary', :id => 'draw_button' %>
      <% end %>
      <%= form_tag discard_piles_path({:room_id => @room.id}), :class => 'form' do %>
        <%= submit_tag 'Discard', :type => "button", :class => 'btn btn-outline-primary', :id => 'discard_button' %>
      <% end %>
      <Button type="button" class="btn btn-outline-primary" id="initiate_transfer_button" action= <%=show_transfer_piles_path({:room_id => @room.id}) %>>Transfer</Button>
      <% if @user_hand.private_pile %>
        <%= render partial: 'partials/show_hand'%>
      <% else %>
        <%= render partial: 'partials/hide_hand'%>
      <% end %>
      <Button type="button" class="btn btn-outline-primary" onclick="changeCards()">Spread/Unspread Cards</Button>
      <% if @fan %>
        <Button type="button" class="btn btn-outline-primary" onclick="fanCards()">Fan/Unfan Cards</Button>
      <% end %>
    </div>
    <div id="dangerous-game-actions">
      <%= link_to 'Exit Game', root_path, :class => 'btn btn-outline-primary' %>
    </div>
  </div>
</div>
<br>

app/views/rooms/new.html.erb
<div class="padded-form">
  <h2>Create New Game Room</h2>
  <%= form_tag rooms_path, :class => 'form' do %>
    <%=label :room, :name, :class => 'col-form-label' %>
    <%= text_field_tag 'room_name', nil  %>
    <%=label :room, :max_players_with_default_5, :class => 'col-form-label'%>
    <%= number_field_tag 'max_players', nil  %>
    <%=label :room, :game_type, :class => 'col-form-label' %>
    <%= text_field_tag 'game_type', nil  %>
    <%=label :room, :private, :class => 'col-form-label' %>
    <%= check_box_tag 'private', nil  %>
     <%= submit_tag 'Create Room', :class => 'btn btn-primary' %>
  <!--  TODO: Add link to home for cancelling addition -->
  <% end %>
</div>

app/views/rooms/new_join.html.erb
<div class="padded-form">
  <h2>Join A Game Room</h2>
  <%= form_tag rooms_create_join_path, :class => 'form', :method=> 'post' do %>
    <%=label :room, :id, 'Room ID', :class => 'col-form-label' %>
    <%= text_field_tag 'id', nil  %>
    <%= submit_tag 'Join Room', :class => 'btn btn-primary' %>
  <% end %>
  <br>
  <%= link_to 'Create Room', new_room_path, :class => 'btn btn-secondary'%>
</div>

app/views/rooms/show.html.erb
<div id='game-room'>
  <%= render partial: 'show_game_room' %>
</div>
<script>
    subscribe_to_room(<%= @room.id %>)
    jQuery(TransferCardsPopup.setup);
    jQuery(DrawsPopup.setup);
    jQuery(DiscardCardsPopup.setup);
    jQuery(CreatePilesPopup.setup);
</script>