config/routes.rb
Rails.application.routes.draw do
  get '/rooms/show_piles', to: 'rooms#show_piles'

  get '/rooms/new_join', to: 'rooms#new_join'
  post '/rooms/create_join', to: 'rooms#create_join'

  post 'rooms/show_hand', to: 'rooms#show_hand'
  resources :rooms

  resources :users

  match '/login', to: 'user_sessions#new', via: :get
  match '/login', to: 'user_sessions#create', via: :post
  match '/logout', to: 'user_sessions#destroy', via: :post
  match '/dashboard', to: 'user_sessions#index', via: :get

  root to: redirect('/dashboard')

  resources :piles do
    collection do
      get 'get_from_draw'
      get 'discard'
      get 'show_transfer'
      post 'draw_cards_from_deck'
      post 'transfer_card'
      post 'transfer_to_discard'
    end
  end
  match '/create_pile', to: 'piles#new', via: :post
  match '/create_deck', to: 'piles#create_deck', via: :post

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def session_params
    params.require(:user).permit(:email, :password)
  end

  def index
    @current_user ||= session[:session_token] && User.find_by_session_token(session[:session_token])
  end

  def new
    render(partial: 'partials/login') if request.xhr?
  end

  def create
    if session_params.has_key?(:password) && session_params.has_key?(:email)
      # Check that the combination gets a user with both

      @current_user = User.where({ email: session_params[:email] }).to_a[0]
      if @current_user&.authenticate(session_params[:password])
        session[:session_token] = @current_user.session_token
        redirect_to dashboard_path, flash: { notice: "Welcome #{@current_user.user_id}.
                                              Your account was successfully logged in." }
        return
      end
    end
    redirect_to login_path, flash: { warning: 'Unsuccessful login' }
  end

  def destroy
    session[:session_token] = nil
    # Maybe should change the session token for next time
    redirect_to dashboard_path, flash: { notice: 'Successfully logged out.' }
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/index.html.erb
<h2>Dashboard</h2>
<% if !@current_user %>
  <%= button_to 'Sign Up/Login',  login_path, method: :get, :class => 'btn btn-primary', :id => 'signupLogin' %>
<% else %>
  <div class="message">
    <%= "Welcome player" %>
  </div>
  <div class="dash-buttons">
    <div class="main-buttons">
      <h2>Create Or Join A Game Room</h2>
      <%= button_to "Create Room", new_room_path, method: :get, :class => 'btn btn-primary' %>
      <%= button_to "Join Room", rooms_new_join_path, method: :get, :class => 'btn btn-primary' %>
      <%= button_to "Logout",  logout_path, method: :post,:class => 'btn btn-primary', :id => 'logout' %>
    </div>
    <div class="my-rooms">
      <h2>My Recent Created Rooms</h2>
      <% Pile.where(:creator =>  @current_user.user_id).order("id DESC").limit(10).each do |pile| %>
        <% associated_room = Room.find(pile.room_id) %>
        <% if associated_room.users.count < associated_room[:max_players] %>
          <%= button_to  associated_room.name, rooms_create_join_path(:id => associated_room.room_code), method: :post, :class => 'btn btn-primary'%>
        <% end %>
      <% end %>
    </div>
    <div class="open-rooms">
      <h2>Available Open Rooms</h2>
      <% Room.where(private: nil).order("id DESC").limit(10).each do |room| %>
        <% if room.users.count < room[:max_players] %>
          <%= button_to  room.name, rooms_create_join_path(:id => room.room_code), method: :post, :class => 'btn btn-primary'%>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<script>
    jQuery(LoginPopup.setup);
</script>

app/views/user_sessions/new.html.erb
<h2>Login</h2>

<%= form_tag login_path, :method => :post, :class => 'form' do %>
  <%= label :user, :email, 'Email',  :class => 'col-form-label'  %>
  <%= text_field :user, 'email', id: 'loginEmail', :class => 'form-control' %>
  <%= label :user, :password, 'Password',  :class => 'col-form-label' %>
  <%= password_field :user, 'password', id: 'loginPass', :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Login to my account', id: 'login_submit' %>
<% end %>
<%= button_to 'Sign-up for an account', new_user_path, :method => :get, id: 'signup' %>